# Generated by Django 4.0.1 on 2022-01-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_time',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
